### PR TITLE
use scipy.io for python dictionary #4

### PR DESCRIPTION
**Pull request by HenryLeongStat**

### CODE REVIEW

**Comment by HenryLeongStat** [comment]
For branchmark, comparing to the start time of MATLAB kernel, both approaches are pretty fast. However, either take a forever when the python dict is too large. I don't have a large memory machine so I can't test it out... But for string approach and 10 millions case, MATLAB somehow used up 14 GB memory in 5 mins, which seems scary; for `scipy.io` approach, python is probably still saving the dict on drive...

**Comment by BoPeng** [comment]
Then use a more reasonable dataset to test.

**Comment by HenryLeongStat** [comment]
for a 1 million case, scipy.io works pretty fast, and string approach fails!

**Comment by BoPeng** [comment]
ok. This justifies the change.

**Comment by HenryLeongStat** [comment]
However, I don't understand how the string approach fails?

**Comment by BoPeng** [comment]
Should be memory issue because it stores everything in memory in an inefficient way.

**Comment by HenryLeongStat** [comment]
I see!

**Pull request merged**
